### ISSUE TITLE
Windows: 'vsvg' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by blowsie** [MMF-FE/svgicon#114]
After installing on windows, the binary / executable is not found, i tried with and without the global flag

```
 npm install vue-svgicon
+ vue-svgicon@4.0.1-alpha.0
added 3 packages from 3 contributors and audited 3 packages in 0.718s
found 0 vulnerabilities

vsvg
'vsvg' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by 7saint** [comment]
try "vue-svgicon": "^3.2.6"

**Comment by CptSpaceToaster** [comment]
The bin is missing again... I'm unsure why `4.0.1-alpha.0` was marked as a suitable version when running `yarn install vue-svgicon`... It's still happening

**Comment by Allenice** [comment]
fixed!!

**Comment by Thomva** [comment]
I'm having the same issue, but with the `@yzfe/vue3-svgicon` package (I can't install `"vue-svgicon": "^3.2.6"` because `vue@"^2.5.17"` can't be resolved)

**Comment by Allenice** [comment]
`@yzfe/vue3-svgicon` is for vue 3+, and SVG icons are loaded by webpack loader `@yzfe/svgicon-loader`. So, `vsvg` is no longer need. Please read the docs for more details: https://mmf-fe.github.io/svgicon/en/
