### ISSUE TITLE
请问前端通过upload上传的svg文件，可以使用@yzfe/svgicon-gen或svgo进行处理吗？

### ISSUE THREAD

**Issue by uCloudCastle** [MMF-FE/svgicon#132]
如题，我试了一下，貌似都依赖node环境，所以在纯前端环境下好像处理不了。
如果是这样的话，对于用户动态添加的svg图标，是否有办法整合进svgicon统一展示？

感谢大佬指点！

**Comment by Allenice** [comment]
@yzfe/svgicon-gen 使用了 svgo, svgo 不能在 browser 环境下运行，你可以找一下有没有 svgo 的浏览器版本。目前还没有办法在纯前端环境（浏览器环境）下处理
