### ISSUE TITLE
vue3 使用 @yzfe/vue-cli-plugin-svgicon 后导致图片无法展示

### ISSUE THREAD

**Issue by catch6** [MMF-FE/svgicon#136]
配置跟官方文档一模一样，使用了@yzfe/vue-cli-plugin-svgicon，结果 img 标签的 src 引入的图片都无法显示，去除此依赖后图片可以正常显示，图片 src 属性我使用的相对路径`<img src="./img/login.png" class="pic">`，这个问题影响挺大的，希望尽早修复

**Comment by Allenice** [comment]
vue-loader v15 用的是 @vue/component-compiler-utils，v16 用的是 @vue/compiler-sfc， 两者对 transformAssetUrls 参数处理的结果不一样，暂时没想到怎么处理，请先参考这个改一下吧：https://github.com/Allenice/svgicon-vue3-demo/blob/master/.vue-svgicon.config.js
