### ISSUE TITLE
react中，可以这样写吗？

### ISSUE THREAD

**Issue by yangjiaqiao** [MMF-FE/svgicon#147]
![image](https://user-images.githubusercontent.com/51978469/114345900-2221b980-9b95-11eb-9783-3272e2eb125f.png)

**Comment by Allenice** [comment]
不可以的, 这是 vue-loader transformassetsurl 的功能。你看看 react 的安装和使用 https://mmf-fe.github.io/svgicon/guide/#%E5%AE%89%E8%A3%85-2
