### ISSUE TITLE
css-what Denial of Service vulnerability 

### ISSUE THREAD

**Issue by shadihrr** [MMF-FE/svgicon#166]
Hi everyone
I use the svgicon for my application and when I am using npm audit I get this result for css-what dependency:
css-what Denial of Service vulnerability 
patched in  >=5.0.1
Dependency of  vue-svgicon  
Path:  vue-svgicon > svgo > css-select > css-what

Do you know what should I do?

**Comment by Allenice** [comment]
svgo updated
