### ISSUE TITLE
vue svgicon display nothing

### ISSUE THREAD

**Issue by mano9dev** [MMF-FE/svgicon#174]
When I use 
 <svgicon
                name="user"
                width="24"
                height="24"
 ></svgicon>

I have this with nothing inside svg
<svg version="1.1" viewBox="0 0 24 24" class="mr-2 svg-icon svg-fill" style="width: 24px; height: 24px;"></svg>

**Comment by mano9dev** [comment]
It's because I didn't import icon from generated icons path

**Comment by sidnaik03** [comment]
@mano9dev Could you please share how you imported the icon? Could you please share sample code? 
Thanks in advance.
