### ISSUE TITLE
error when starting dev server: TypeError: svgicon is not a function

### ISSUE THREAD

**Issue by BD-zhang** [MMF-FE/svgicon#205]
vite.config.js can not recognize svgcion from, 
sow when i check the dist file from node_modules, 
i found the function is derived like this
![image](https://user-images.githubusercontent.com/59193698/199146853-317e2236-622f-44ab-9b29-cec21842cafc.png)
so i use 
![image](https://user-images.githubusercontent.com/59193698/199147138-82fd5f59-c952-4a58-afad-85ad277441cc.png)
instead of what official suggest us doing....
the official introduction example needs updating !!!

**Comment by Allenice** [comment]
I think this is related to your project configuration.
