### ISSUE TITLE
预览显示的是绝对路径？

### ISSUE THREAD

**Issue by raohuiyong** [MMF-FE/svgicon#220]
使用@yzfe/svgicon-viewer进行svg文件夹的预览页面时显示的文件名如下
D:/Users/deepcam/Documents/deepcamGit/VisionCraft/webSource/src/icons/svg/aiLabel/arrows

需求：
页面中使用svg组件方式是 
```vue
<svg-icon name="aiLabel/arrows" />
```
在预览的时候如何保持一致的风格？不显示路径，只显示相应的name名？
把D:/Users/deepcam/Documents/deepcamGit/VisionCraft/webSource/src/icons/svg/aiLabel/arrows替换成aiLabel/arrows进行显示

![image](https://github.com/MMF-FE/svgicon/assets/26049430/98ad1aee-e584-4152-befd-ebcb9c8bda9e)

**Comment by Allenice** [comment]
预览图标请使用相对路径，比如：`svgicon-viewer ./src/assets/svgicon`

**Comment by raohuiyong** [comment]
@Allenice  使用你推荐的方法，win10上无效
