### ISSUE TITLE
Accessible suggestion

### ISSUE THREAD

**Issue by sebmor** [MMF-FE/svgicon#83]
Would potentially be a quick improvement to the package if it would support some basic default a11y settings;

```
<svg role="img" aria-labelledby="icon-title">
  <title id="icon-title">{iconName}</title>
  <path ...>
</svg>
```

**Comment by Allenice** [comment]
Why not use aria-label?
```html
<svg aria-label="iconName or title prop ">
  <path ...>
</svg>
```
vue-svgicon has `title` prop to add SVG title element.

**Comment by sebmor** [comment]
All documentation I could find used aria-labelledby for SVGs, but after checking the docs on aria I suppose why not, it says it can be used on all html elements.
