### ISSUE TITLE
Unknown custom element: <svg-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option

### ISSUE THREAD

**Issue by shawn-tangsc** [MMF-FE/svgicon#93]
在跑vue-cli 3.0 的test:unit 时 报了这个错，选的时jest

  [Vue warn]: Unknown custom element: < svg-icon > - did you register the component correctly? For recursive components, make sure to provide the "name" option

**Comment by whoacowboy** [comment]
I believe the default component name is `<svgicon>` without the hyphen.
