### ISSUE TITLE
How to pass color to svgicon through css

### ISSUE THREAD

**Issue by sidnaik03** [MMF-FE/svgicon#94]
Hi,
I have just started using this library. I have one query regarding css. 
When I passed inline color property , its get applied to the icon.
`<svgicon class="svg-icon" name="copy" slot="activator" @click="createEvent(copyObject.selectType, 'onCopy')" color="red black"></svgicon>` 

This display icon properly.

But when i passed the same color option using css, The icon get filled only with red color. My css class is like 
`.svg-icon {
    width:100px;
    height:100px; 
    color:red black;
}`

Also tried this also. But not working
`.vue-icon path[pid='0'] {
    fill: #42b983;
}
.vue-icon path[pid='1'] {
    fill: #35495e;
}`
Please help.

**Comment by Allenice** [comment]
You can use the inspector to see the html structure and style of the svg icon.
