### ISSUE TITLE
svg reference in css

### ISSUE THREAD

**Issue by crow7m** [MMF-FE/svgicon#96]
First Thanks for module.
I have small issue with  svg reference in my css, for background image so this  
`background-image: url(../../assets/svg/target_icon_white.svg);`
will produce this in browser  el -> backgound-image: [object, object],
 
I am using version 4, and here is my vue.config 

` const path = require('path');
           const svgFilePath = path.join(__dirname, './src/assets/svg');
`
 `module.exports = {
            publicPath:
               process.env.NODE_ENV === 'production' ? '/vue-svgicon/v4/' : '/',
            outputDir: 'dist/v4',
            chainWebpack: config => {
              // config.entry('style').add('../..src/styles/app.scss')
              const svgFontRule = config.module
                 .rule('vue-svgicon')
                 .test(/\.svg$/)
                 .use('svgicon')
                 .loader('@yzfe/vue-svgicon-loader')
                 .options({
                   idSeparator: '_',
                   svgFilePath,
                 });`

      `config.module
           .rule('vue')
           .use('vue-loader')
           .loader('vue-loader')
           .tap(options => {
               options.transformAssetUrls = options.transformAssetUrls || {}
               options.transformAssetUrls['it-icon'] = ['data'];
               return options
           });
        config.module.rule('svg').exclude.add(svgFilePath);
        config.resolve.alias.set('@it-icon', svgFilePath);
        config.resolve.symlinks(true);
    }}`
I have a folder for static svgs - staticSvg, 
anyway i can exclude it from vue-svgicon-loader so i will be able to reference those resources via regular require in js, and regular backgound-image url() in css ?
Thank you for your help

**Comment by Allenice** [comment]
You can use resource query: https://webpack.js.org/configuration/module/#ruleresourcequery
