### ISSUE TITLE
Cannot assign to read only property 'exports' of object

### ISSUE THREAD

**Issue by Skylercrane23** [MMF-FE/svgicon#97]
I am currently working on creating a company npm package built around vue-svgicon to be able to have all our icons in source control to be used across multiple vue projects (Vue CLI, and Nuxt Projects).

The goal is for us to be able to drop in new svg files and generate the components and publish the package to be consumed by our outher projects. In our other projects we would just have the vue-svgicon package installed so we can use the `<svgicon icon="agent"></svgicon>` syntax. 

**The Issue:**

 When I use vue-svg directly in my nuxt project it works as expected but when I use it from my  npm package (using npm link since I don't want it published yet) I encounter errors. The icon is showing up right now but I keep getting `Cannot assign to read only property 'exports' of object` in the console that is connected to `svgicon.common.js` with the error occurring at the `module.exports` part as well as `./node_modules/icon-test/homie-icons/agent.js 11:0-4"export 'default' (imported as 'icon') was not found in 'vue-svgicon'` error

**My Setup**

In my nuxt project I am using the plugin syntax:
 `plugins: [{ src: '~/plugins/vue-svgicon' }],` in my `nuxt.config.js` 

the actual plugin  (`vue-svgicon.js`) looks like this:
```
import Vue from 'vue'
import VueSVGIcon from 'vue-svgicon'

Vue.use(VueSVGIcon)
```

and then in the build section:
```
build: {
    transpile: ['icon-test'],
    extend(config, ctx) {
      config.resolve.symlinks = false
    }
  }
```

the `config.resolve.symlinks = false` line when commented out has no console errors but the icon flashes for a second and then disappears. So this issue could also be related to that. 

Then in my vue component I am referencing the icon like this:
`<svgicon icon="agent" class="h-16 w-16 fill-current stroke-none text-red block relative"></svgicon>`
Note: I am using tailwindcss for styling the icons which is working fine.

and then in the script section I am importing it like this:
`import 'icon-test/homie-icons/agent'` => this is referencing the linked npm package in my node modules. 

In my npm package that is being linked my package.json is like this:
```
{
  "name": "icon-test",
  "version": "1.0.0",
  "description": "",
  "main": "./homie-icons/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "generate-icons": "vsvg -s ./icon-files -t ./homie-icons --es6"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "vue-svgicon": "^3.2.6"
  }
}
```

Only thing I changed was having the entry point be the `index.js` file that is generated after the svg's have been generated. `icon-files` is the raw svg icons, and the homie-icons is where they are being compiled to. 

Any insights would be greatly appreciated!

**Comment by Allenice** [comment]
Is it using babel? Try not to exclude **node_modules/your_icon_package** or try vue-svgicon 4.x

**Comment by Skylercrane23** [comment]
@Allenice which part is excluding it? The transpile section In the build I think is whitelisting it. But without it, the icons don’t show.
